language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t sujithnair711/docker-react .
script:
  - docker run -e CI=true sujithnair711/docker-react 
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-364202389140"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESSKEY
  secret_access_key: $AWS_SECRETKEY
