language: generic
sudo: required
service:
  - docker
before_install:
  - docker build -t sujithnair711/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true sujithnair711/docker-react npm run test

